development:
  adapter: postgresql
  database: jai_class #jai_training
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  adapter: postgresql
  database: jai_class #jai_training
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test: 
  adapter: postgresql
  database: jai_class_test #jai_training
  username: postgres
  password: postgres
  host: localhost
  port: 5432
